### ISSUE TITLE
"[Errno 2] No such file or directory" when attempting to convert JSON to Tab

### ISSUE THREAD

**Issue by ghost** [olety/epwing2kindle#2]
**Describe the bug**
In the 3rd step, converting the JSON to Tab, python on my computer doesn't seem to be able to recognise yomi2tab.py and gives me the error in the screenshot. I have yomi2tab.py in my working folder. Should I try to use 3.6 instead? I might be messing up something really obvious, I've never used Python before

**Screenshots**
![default](https://user-images.githubusercontent.com/40442162/47840552-8e861500-ddae-11e8-86c7-ad29dea5775c.png)

**PS:**
For clarification; I used "py -3.7" in the screenshot above but it returns the same error if i write "py -3" and if i use a different directory on a different disc

**Comment by olety** [comment]
Hi, thanks for opening an issue!

Could you please run the `dir *.*` command in the same directory and post the screenshot here? I'd like to make sure that the yomi2tab.py file is indeed there.

**Comment by ghost** [comment]
![default](https://user-images.githubusercontent.com/40442162/47900656-8a70fa80-de75-11e8-8237-ab52615ad49e.png)
Thanks for responding so quickly! I ran the `dir *.*` command and this is what I got. So the yomi2tab.py is indeed there

**Comment by olety** [comment]
No problem man, thanks for providing the screenshots 😄 

I think that I might've figured out the root cause of the problem we're dealing with here: the files have to be in your current *working directory*, not in the python's folder. 

So, when you run `py -3.7 yomi2tab.py -o mydict.tab "C:\Users\Dara\Desktop\daijirin"`, the yomi2tab.py file has to be in the folder you're currently in as well. (I.e. if you were to run this command while being in `...\Python\Python37` everything should work; or you could just move the file to whatever folder you prefer to use as your "workplace")

Please try out any of the options above and let me know what happens :)

**Comment by ghost** [comment]
Yes! That was it! Thanks for making this tool, I was able to make my .mobi
![img_20181102_111648](https://user-images.githubusercontent.com/40442162/47912808-be5a1900-de91-11e8-92f9-3f8f8b7b2274.jpg)

**Comment by olety** [comment]
Thanks for using it! And have fun with AJATT/MIA ^_^
